application: sutsis
version: redesign
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /lib
  static_dir: lib
  secure: always
- url: /data
  static_dir: data
  expiration: "90d"
  secure: always
- url: /components
  static_dir: bower_components
  secure: always
- url: /
  static_files: index.html
  upload: index.html
  secure: always
- url: /search/.*
  static_files: index.html
  upload: index.html
  secure: always
- url: /search.js
  static_files: search.js
  upload: search.js
  secure: always
- url: /worker.js
  static_files: worker.js
  upload: worker.js
  secure: always
- url: /lujvo.js
  static_files: lujvo.js
  upload: lujvo.js
  secure: always
- url: /parseXML.html
  static_files: parseXML.html
  upload: parseXML.html
  secure: always
- url: /webapp.appcache
  static_files: webapp.appcache
  upload: webapp.appcache
  secure: always
