application: sutyvlaste
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /lib
  static_dir: lib
  secure: always
- url: /data
  static_dir: data
  expiration: "90d"
  secure: always
- url: /
  static_files: index.html
  upload: index.html
  secure: always
